spring:
  application:
    name: ClinicalAgenda

  datasource:
    url: jdbc:postgresql://localhost:5435/ClinicalAgenda
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key-123456789-clinical-agenda-portfolio}

  logging:
  level:
    org.springframework.security: DEBUG